"""Initial migration

Revision ID: be527742fbf8
Revises: 
Create Date: 2026-02-02 11:11:13.838293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be527742fbf8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caregiver',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('user_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caregiver_email'), 'caregiver', ['email'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('caregiver_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminder',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('caregiver_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['caregiver_id'], ['caregiver.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminder_status',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('reminder_id', sa.UUID(), nullable=True),
    sa.Column('_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminder_status')
    op.drop_table('reminder')
    op.drop_table('user')
    op.drop_index(op.f('ix_caregiver_email'), table_name='caregiver')
    op.drop_table('caregiver')
    # ### end Alembic commands ###
